name: tmnext-in

services:
  app:
    image: cxnext-app:v1
    pull_policy: never
    build:
      context: ../../..
      dockerfile: .container/Dockerfile
    container_name: tmnext-in-app
    ports:
      - "4002:4000"
      - "5002:4000"
    restart: unless-stopped
    volumes:
      - tmnext_in_runtime:/opt/cxnext/runtime
    networks:
      - codexion-network

volumes:
  tmnext_in_runtime:

networks:
  codexion-network:
    external: true
    name: codexion-network
