name: tirupur-direct

services:
  app:
    image: cxnext-app:v1
    pull_policy: never
    build:
      context: ../../..
      dockerfile: .container/Dockerfile
    container_name: tirupur-direct-app
    ports:
      - "4001:4000"
      - "5001:4000"
    restart: unless-stopped
    volumes:
      - tirupur_direct_runtime:/opt/cxnext/runtime
      - ./tirupur-direct.env:/opt/cxnext/runtime/.env
    networks:
      - codexion-network

volumes:
  tirupur_direct_runtime:

networks:
  codexion-network:
    external: true
    name: codexion-network
