name: cxnext

services:
  app:
    build:
      context: ..
      dockerfile: .container/Dockerfile
    container_name: cxnext-app
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - cxnext_runtime:/opt/cxnext/runtime
    networks:
      - codexion-network

volumes:
  cxnext_runtime:

networks:
  codexion-network:
    external: true
    name: codexion-network
